export const NODE_SYSTEM_CONTAINER_PADDING = 50;

export const NODE_WIDTH = 300;

export const NODE_BASE_HEIGHT = 200; // Some Assets cause images to be larger

export const NODE_DAGRE_WIDTH = NODE_WIDTH + NODE_SYSTEM_CONTAINER_PADDING * 2;
export const NODE_DAGRE_HEIGHT =
	NODE_BASE_HEIGHT + NODE_SYSTEM_CONTAINER_PADDING * 2;
